


#=============================================================
FROM openjdk:8u111-jdk
MAINTAINER smita Mutha<smita_mutha@syntelinc.com>

#RUN mkdir /app
#COPY ./complete /app
#WORKDIR /app
ADD WCloudAccountService.jar WCloudAccountService.jar
CMD java -Dspring.profiles.active=dev -jar WCloudAccountService.jar
